import BarListHeading from "./components/atoms/BarListHeading.svelte"
import BarListHeadingDate from "./components/atoms/BarListHeadingDate.svelte"
import BarTitle from "./components/atoms/BarTitle.svelte"
import Button from "./components/atoms/Button.svelte"
import ButtonFill from "./components/atoms/ButtonFill.svelte"
import ButtonOutline from "./components/atoms/ButtonOutline.svelte"
import Input from "./components/atoms/Input.svelte"
import Tabmenu from "./components/atoms/Tabmenu.svelte"
import Test from "./components/widgets/Test.svelte"
export const routes = {"/atoms/BarListHeading": BarListHeading,"/atoms/BarListHeadingDate": BarListHeadingDate,"/atoms/BarTitle": BarTitle,"/atoms/Button": Button,"/atoms/ButtonFill": ButtonFill,"/atoms/ButtonOutline": ButtonOutline,"/atoms/Input": Input,"/atoms/Tabmenu": Tabmenu,"/widgets/Test": Test}